name: "Build Release"
on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '*'

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: path_of_oil

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot -v --export "Windows Desktop" build/windows/${EXPORT_NAME}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: windows
          path: build/windows
          
  export-linux-64:
    name: Linux 64 Bit Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux 64 bit" build/linux/${EXPORT_NAME}_64_bits.x86_64
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: linux64
          path: build/linux

  export-linux-32:
    name: Linux 32 Bit Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          godot -v --export "Linux 32 bit" build/linux/${EXPORT_NAME}_32_bits.x86
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: linux32
          path: build/linux

  export-mac:
    name: Mac Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot -v --export "Mac OSX" build/mac/${EXPORT_NAME}.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: mac
          path: build/mac

  removeArtifacts:
    needs: [deployToSteam]
    runs-on: ubuntu-latest
    steps:
    - name: Remove artifacts
      # You may pin to the exact commit or the version.
      # uses: c-hive/gha-remove-artifacts@24dc23384a1fa6a058b79c73727ae0cb2200ca4c
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        # Artifacts older than this will be deleted (e.g. "2 months", "1 day"). Parsed by moment.
        age: "5 minutes"
        # Access token for the repository, available under the same name in secrets.
        GITHUB_TOKEN: ${{ github.token }}